### ISSUE TITLE
Items supporting braille updates

### ISSUE THREAD

**Issue by EvanSchallerer** [osu-cass/SampleItemsWebsite#167]
- [x]  If an item supports braille, add a link similar to "performance item" above iframe #223
- [x] Add Supported Braille types to Sample Item (Context) #220
- [x] Disable accessibility options for item if file does not exists #221
- [x] Zip of all passage and item based on braille type #222
- [x] Enable accessibility resource family braille options #224
- [x]  Streamlined mode #225

url: ftp://ftps.smarterbalanced.org/~sbacpublic/
Public/PracticeAndTrainingTests/2016-2017_PracticeAndTrainingBrailleFiles/<subject>/<grade>/item-<itemid>/{braille files}

where <subject> is either Math or ELA, <grade> is the two digit grade, and <itemid> is the item id.  
Example Url:
http://localhost:20529/Item/Braille?bankKey=187&itemKey=2558&brailleCode=TDS_BT_EXN

**Comment by alexlepinski** [comment]
https://gist.github.com/alexlepinski/d782e40f7c194c79c6943e87e7ddbf23

**Comment by struthj** [comment]
Question for the smarter balanced team? What do they want for performance items with braille?

**Comment by Garrett-S** [comment]
Question for SB team? Is the braille always English? Or is it sometimes Spanish?

**Comment by Garrett-S** [comment]
#233 adds an animation to the download link when the user is waiting for it to start.

**Comment by Garrett-S** [comment]
This has been merged into milestone 3.
